library("igraph")
library("ggnet")
edges <- read.csv("data.txt")
g = graph.data.frame(edges, directed = FALSE )
adjlist <- get.adjedgelist(g)
#plot.igraph(g)
png(file="mygraphic.png",width=2048,height=2048, res=150)
ggnet(edges, size = 12, color = 'grey', label=TRUE, label.size = 2)
dev.off()